export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_ADDRESS = "FETCH_EVENTS_ADDRESS";
export const FETCH_EVENTS_BY_ID = "FETCH_EVENTS_BY_ID";
export const FETCH_EVENTS_COUNT = "FETCH_EVENTS_COUNT";