export const FETCH_EVENTS = "FETCH_EVENTS";
export const FETCH_EVENTS_IMAGE = "FETCH_EVENTS_IMAGE";
export const FETCH_EVENTS_BY_ID = "FETCH_EVENTS_BY_ID";
export const FETCH_EVENTS_COUNT = "FETCH_EVENTS_COUNT";
export const FETCH_EVENTS_TYPE = "FETCH_EVENTS_TYPE";
export const FETCH_EVENT_TIMESERIES_DATA = "FETCH_EVENT_TIMESERIES_DATA";
